# Generated by Django 5.0 on 2023-12-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_sitecontact_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteContact',
            new_name='Contact',
        ),
    ]
